In [ ]:
# Analysing and Visualizing Data Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import metrics, tree
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Spliting Libraries
from sklearn.model_selection import train_test_split

# Logistic Regression Libraries
from sklearn.linear_model import LogisticRegression

# Random Forest Libraries
from sklearn.ensemble import RandomForestClassifier

# Making Diffrent Models and downloading them
from google.colab import files
import joblib

#**Importing Datasets**

In [ ]:
%pip install ucimlrepo

In [ ]:
# Import the dataset into your code
from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)


{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M

#**Printing Head**

In [ ]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0

In [ ]:
y.head()

num
0    0
1    2
2    1
3    0
4    0

#**Printing info**

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
dtypes: float64(3), int64(10)
memory usage: 30.9 KB


In [ ]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   num     303 non-null    int64
dtypes: int64(1)
memory usage: 2.5 KB


#**Checking Nulls**

In [ ]:
X.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
dtype: int64

In [ ]:
y.isnull().sum()

num    0
dtype: int64

#**Print Describtion**

In [ ]:
X.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.672241   
std      0.994971   22.875003    0.469794    1.161075    0.616226    0.937438   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

             thal  
count  301.000000  
mean     4.734219  
std      1.939706  
min      3.000000  
25%      3.000000  
50%      3.000000  
75%      7.000000  
max      7.000000

#**Print Unique Values**

In [ ]:
print("the uniqe values of thal:")
X['thal'].unique()

the uniqe values of thal:


array([ 6.,  3.,  7., nan])

In [ ]:
print("the uniqe values of the cp : ")
X['cp'].unique()

the uniqe values of the cp : 


array([1, 4, 3, 2])

In [ ]:
print("the uniqe values of the sex : ")
X['sex'].unique()

the uniqe values of the sex : 


array([1, 0])

In [ ]:
# Changing Num to Target
y['target'] = y['num']
y.drop('num', axis=1, inplace=True)

In [ ]:
print("the uniqe values of the target : ")
y['target'].unique()

the uniqe values of the target : 


array([0, 2, 1, 3, 4])

#**Analyzing Important Features**

In [ ]:
countNoDisease = len(y[y.target == 0])
countHaveDisease = len(y[y.target == 1])
print("Percentage of Patients Haven't Heart Disease: {:.2f}%".format((countNoDisease / (len(y.target))*100)))
print("Percentage of Patients Have Heart Disease: {:.2f}%".format((countHaveDisease / (len(y.target))*100)))

Percentage of Patients Haven't Heart Disease: 54.13%
Percentage of Patients Have Heart Disease: 18.15%


#**Concatenate Data Frames**

In [ ]:
df = pd.concat([X, y], axis=1, join='outer')

#**Drop Duplicates**

In [ ]:
print(df.duplicated().sum())
df = df.drop_duplicates()

0


#**Cliping OutLiears**

In [ ]:
def clip_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)

    return df

In [ ]:
outlier_columns = ['trestbps', 'chol', 'fbs',	'restecg', 'thalach',	'exang', 'oldpeak',	'slope', 'ca', 'thal']

for col in outlier_columns:
    df = clip_outliers(df, col)

#**Exporting Data After Cleaning**

In [ ]:
df.to_csv("Heart_Disease_Project/data/heart_disease.csv", index=False)
#df.to_csv("heart_disease.csv", index=False)